#ifndef GUARD_CONSTANTS_SPEAKER_NAMES_H
#define GUARD_CONSTANTS_SPEAKER_NAMES_H

enum SpeakerNames {
    SP_NAME_NONE = 0,
    SP_NAME_MOM,
    SP_NAME_PLAYER,
	SP_NAME_NURSE,
	SP_NAME_BIRCH,
	SP_NAME_MOMBRENDAN,
	SP_NAME_MOMMAY,
	SP_NAME_BRENDAN,
	SP_NAME_MAY,
	SP_NAME_SCOTT,
	SP_NAME_EXECUTIVE,
	SP_NAME_AQUA_GRUNT,
	SP_NAME_MAGMA_GRUNT,
    SP_NAME_COUNT
};

#endif // GUARD_CONSTANTS_SPEAKER_NAMES_H
